### PR TITLE
micro optimizations with type() and is[VARTYPE]

### PR DESCRIPTION
**Pull request by ExtReMLapin**

### CODE REVIEW

**Comment by Nayruden** [comment]
Thank you for your submission! We value our community and we love getting PRs or other code suggestions.

Unfortunately, your changes are not improvements to the original code. `istable`, `isstring`, etc are wrappers for Lua type checking, and they are an artifact particular to GM-Lua only. We try to avoid using GM-Lua conventions when possible if there's not a major performance hit. In this case, performance should be similar (I would guess `isstring` would be slightly slower, though).

**Comment by ExtReMLapin** [comment]
I get a 5-7% performance boost on `ULib.makeKeyValues`

**Comment by ExtReMLapin** [comment]
Literally faster

**Comment by Nayruden** [comment]
I am honestly shocked that the wrapper would be faster, but either way, we prefer edging away from GM-Lua specifics

**Comment by Kefta** [comment]
They're not wrappers, they're C funcs. They're faster than ``type`` since a string doesn't have to be pushed to Lua, and the code doesn't have to return to C for the string comparison.

**Comment by ItsEris** [comment]
no wonder ULX/ULib are slow as asshole

**Pull request closed without merging**
