### PR TITLE
CAMI repo structure has been changed

### PR DESCRIPTION
**Pull request by djtb2924**
Since https://github.com/glua/CAMI/commit/a026647dd9545a338ca57436bcaaea341cf588eb the old CAMI link went error
+ CAMI has been updated

### CODE REVIEW

**Comment by djtb2924** [comment]
@Nayruden ?

**Comment by Nayruden** [comment]
Yes?

**Comment by djtb2924** [comment]
Will the PRs be approved ?

**Comment by Nayruden** [comment]
The PRs / outstanding issues get reviewed and processed from the oldest modification date to newest as time allows. Unfortunately, time for the devs has been at a premium lately. It's something I am actively trying to resolve.

**Comment by zpetty33** [comment]
This is outdated. It's true our CAMI implementation needs to be updated, but this PR is a few versions old.

**Pull request closed without merging**
